# This is a basic workflow to help you get started with Actions

name: GitHub-staging

on:
  push:
    branches: [ staging ]
    

jobs:
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Push to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    


